# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev
#variables
variables:
  tag: "$(Build.BuidID)"

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build_Stage
    displayName: Build_Stage
    jobs:
     - job : Build
       displayName: Build_stage
       pool: 
        vmImage: "ubuntu-latest"
       steps:
        #Task1 : Build Docker image and push it to ACR
        - task: Docker@2
          inputs:
            containerRegistry: 'vyshakaks'
            repository: 'custome2nginxapp1'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: 
              $(tag)
              $(Build.SourceVersion)
    
      #Task2 : Copy Kube manifest files to artifactory
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
            OverWrite: true

      #Task3 :Publish Build Artifacts to Az Pipeline
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'droplocation'
            publishLocation: 'Container'

